# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'color_calibrator.ui'
#
# Created by: PyQt4 UI code generator 4.12.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_ColorCalibrator(object):
    def setupUi(self, ColorCalibrator):
        ColorCalibrator.setObjectName(_fromUtf8("ColorCalibrator"))
        ColorCalibrator.resize(728, 895)
        self.centralwidget = QtGui.QWidget(ColorCalibrator)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.HLow = QtGui.QSlider(self.centralwidget)
        self.HLow.setGeometry(QtCore.QRect(140, 720, 160, 16))
        self.HLow.setMaximum(255)
        self.HLow.setOrientation(QtCore.Qt.Horizontal)
        self.HLow.setObjectName(_fromUtf8("HLow"))
        self.SLow = QtGui.QSlider(self.centralwidget)
        self.SLow.setGeometry(QtCore.QRect(140, 750, 160, 16))
        self.SLow.setMaximum(255)
        self.SLow.setOrientation(QtCore.Qt.Horizontal)
        self.SLow.setObjectName(_fromUtf8("SLow"))
        self.VLow = QtGui.QSlider(self.centralwidget)
        self.VLow.setGeometry(QtCore.QRect(140, 780, 160, 16))
        self.VLow.setMaximum(255)
        self.VLow.setOrientation(QtCore.Qt.Horizontal)
        self.VLow.setObjectName(_fromUtf8("VLow"))
        self.HUpper = QtGui.QSlider(self.centralwidget)
        self.HUpper.setGeometry(QtCore.QRect(380, 720, 160, 16))
        self.HUpper.setMaximum(255)
        self.HUpper.setOrientation(QtCore.Qt.Horizontal)
        self.HUpper.setObjectName(_fromUtf8("HUpper"))
        self.SUpper = QtGui.QSlider(self.centralwidget)
        self.SUpper.setGeometry(QtCore.QRect(380, 750, 160, 16))
        self.SUpper.setMaximum(255)
        self.SUpper.setOrientation(QtCore.Qt.Horizontal)
        self.SUpper.setObjectName(_fromUtf8("SUpper"))
        self.VUpper = QtGui.QSlider(self.centralwidget)
        self.VUpper.setGeometry(QtCore.QRect(380, 780, 160, 16))
        self.VUpper.setMaximum(255)
        self.VUpper.setOrientation(QtCore.Qt.Horizontal)
        self.VUpper.setObjectName(_fromUtf8("VUpper"))
        self.label = QtGui.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 720, 21, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(100, 750, 21, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.label_3 = QtGui.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(100, 780, 21, 16))
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.label_4 = QtGui.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(200, 690, 67, 17))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.label_5 = QtGui.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(440, 690, 67, 17))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.cameraComboBox = QtGui.QComboBox(self.centralwidget)
        self.cameraComboBox.setGeometry(QtCore.QRect(120, 10, 161, 21))
        self.cameraComboBox.setObjectName(_fromUtf8("cameraComboBox"))
        self.cameraComboBox.addItem(_fromUtf8(""))
        self.cameraComboBox.addItem(_fromUtf8(""))
        self.label_6 = QtGui.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(20, 10, 91, 21))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.label_7 = QtGui.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(20, 50, 111, 21))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.pushButton = QtGui.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(140, 50, 89, 25))
        self.pushButton.setObjectName(_fromUtf8("pushButton"))
        self.cameraButton = QtGui.QPushButton(self.centralwidget)
        self.cameraButton.setGeometry(QtCore.QRect(290, 10, 89, 25))
        self.cameraButton.setObjectName(_fromUtf8("cameraButton"))
        self.label_8 = QtGui.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(20, 90, 101, 21))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.namefileEdit = QtGui.QLineEdit(self.centralwidget)
        self.namefileEdit.setGeometry(QtCore.QRect(120, 90, 113, 25))
        self.namefileEdit.setCursor(QtGui.QCursor(QtCore.Qt.IBeamCursor))
        self.namefileEdit.setObjectName(_fromUtf8("namefileEdit"))
        self.saveButton = QtGui.QPushButton(self.centralwidget)
        self.saveButton.setGeometry(QtCore.QRect(250, 90, 89, 25))
        self.saveButton.setObjectName(_fromUtf8("saveButton"))
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(40, 670, 561, 151))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.label_9 = QtGui.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(40, 640, 111, 21))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.imageLable = QtGui.QLabel(self.centralwidget)
        self.imageLable.setGeometry(QtCore.QRect(40, 140, 640, 480))
        self.imageLable.setFrameShape(QtGui.QFrame.Panel)
        self.imageLable.setText(_fromUtf8(""))
        self.imageLable.setObjectName(_fromUtf8("imageLable"))
        self.frame.raise_()
        self.HLow.raise_()
        self.SLow.raise_()
        self.VLow.raise_()
        self.HUpper.raise_()
        self.SUpper.raise_()
        self.VUpper.raise_()
        self.label.raise_()
        self.label_2.raise_()
        self.label_3.raise_()
        self.label_4.raise_()
        self.label_5.raise_()
        self.cameraComboBox.raise_()
        self.label_6.raise_()
        self.label_7.raise_()
        self.pushButton.raise_()
        self.cameraButton.raise_()
        self.label_8.raise_()
        self.namefileEdit.raise_()
        self.saveButton.raise_()
        self.label_9.raise_()
        self.imageLable.raise_()
        ColorCalibrator.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(ColorCalibrator)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 728, 22))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuColorCalibrator = QtGui.QMenu(self.menubar)
        self.menuColorCalibrator.setObjectName(_fromUtf8("menuColorCalibrator"))
        ColorCalibrator.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(ColorCalibrator)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        ColorCalibrator.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuColorCalibrator.menuAction())

        self.retranslateUi(ColorCalibrator)
        QtCore.QMetaObject.connectSlotsByName(ColorCalibrator)

    def retranslateUi(self, ColorCalibrator):
        ColorCalibrator.setWindowTitle(_translate("ColorCalibrator", "MainWindow", None))
        self.label.setText(_translate("ColorCalibrator", "H", None))
        self.label_2.setText(_translate("ColorCalibrator", "S", None))
        self.label_3.setText(_translate("ColorCalibrator", "V", None))
        self.label_4.setText(_translate("ColorCalibrator", "Lower", None))
        self.label_5.setText(_translate("ColorCalibrator", "Upper", None))
        self.cameraComboBox.setItemText(0, _translate("ColorCalibrator", "Webcam", None))
        self.cameraComboBox.setItemText(1, _translate("ColorCalibrator", "ExternalCamera", None))
        self.label_6.setText(_translate("ColorCalibrator", "VideoDevice", None))
        self.label_7.setText(_translate("ColorCalibrator", "GetFile Config", None))
        self.pushButton.setText(_translate("ColorCalibrator", "Browse", None))
        self.cameraButton.setText(_translate("ColorCalibrator", "Open", None))
        self.label_8.setText(_translate("ColorCalibrator", "Save Config", None))
        self.namefileEdit.setText(_translate("ColorCalibrator", "name_file", None))
        self.saveButton.setText(_translate("ColorCalibrator", "Save", None))
        self.label_9.setText(_translate("ColorCalibrator", "HSV Calibrator", None))
        self.menuColorCalibrator.setTitle(_translate("ColorCalibrator", "ColorCalibrator", None))

